name: Deploy Web

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  JAVA_VERSION: 17

permissions:
  pull-requests: write

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Generate Artifact
        run: "./gradlew :webApp:wasmJsBrowserDistribution"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webApp/build/dist/wasmJs/productionExecutable
          destination_dir: "./"
